const Disclaimer=()=> {
  return (
    <div className="bg-white border-8 rounded-xl shadow p-6 mt-6 text-sm text-gray-800">
      <h2 className="font-bold  mb-2">Disclaimer</h2>
      <p className="font-size">
        Results generated by the calculator(s) are indicative in nature. The interest rate applied on the loan will
        depend on the prevailing rates at the time of loan booking. The calculator(s) is not intended to provide its
        users/ customers with results that are either certified by Bajaj Finance Limited (“BFL”) or are an obligation,
        assurance, warranty, undertaking or commitment, financial and professional advice by BFL, under any
        circumstances. The calculator(s) is only a tool that assists the users/ customers arrive at the results of
        various illustrative scenarios generated from data input by the user/ customer. The use of the calculator is
        entirely at the risk of the user/ customer, BFL is not responsible for any reason, for any errors in any outcome
        resulting from the use of the calculator.
      </p>
    </div>
  );
}
export default Disclaimer;